language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: Kj552in51cMrZqgPHLX6FQWx0IWRrRAxwv0tlBc0lN55ZJl5gYauxP7XqDjweZrN1NqJRZ8++ufTjGR2/Kx3JtmirVM4aM3Qu4l4xqCemr1YKeno6r5peGwhg9+RjFtWXLNiUXu1Fs2N9nXOLXZJCcvwu3tXlzJ1WwQyTP70aqCqDW0FDBeDA4OlteJVSI96QHMvvGvdX2MvWAmt1Uu6HHFjmeRngJGm/yIJcb4imwy7RF8e+ZpFOQ5V8+cpjyRUgKuEgd3P4AmH+Zh/+uX9RcQw2HSl+tQ/9kjODl0a4stbKBVT49qrKtjMy0gwVN1I1/iNRKX0OyHLa4PBPdLorgRBq46rCvYT6BLNlL/UuLkrRq6LRVQxASE2VyoW80iqKTMTAmzzDK6P4i+Rgs6vWKjOMraCnT4hOupDOrjLOP+DanHK3jfBeVUh1ggmtmd5QS+bjXVNCOAQStHPdjbvjC5TyVg22dHxchdFs1Ldmyupgq4dgpZWNgl9LlhVUGNxzDKDOk0/sqA5Gts2qJ70pMpUzIpI1lPIBn3Xa9pWpxxabRh7V1jO4vNVbcFAwteGPg5ie1Nj1XxFRfPU9YbqBnWjAStvXeVAA/z/Ocaj5VCzCoUWUanpjE3aQ4LUNciVwNPqVXtQP4eWBtrjnv2HEEn5/7hvaMIYYVdwl1F7WMA=
