package de.codecentric.maschinenmeister.outside.api;

/**
 * Created by stefansiprell on 20.02.17.
 */
public enum ConnectReturnCode {

    CONNECTION_ACCEPTED, CONNECTION_REFUSED_UNACCEPTABLE_PROTOCOL_VERSION, CONNECTION_REFUSED_IDENTIFIER_REJECTED,
    CONNECTION_REFUSED_SERVER_UNAVAILABLE, CONNECTION_REFUSED_BAD_USERNAME_OR_PASSWORD, CONNECTION_REFUSED_NOT_AUTHORIZED

}
